version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=icommerce
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
  sqs:
    image: s12v/elasticmq:latest
    ports:
      - "9324:9324"
  sqs-create:
    image: infrastructureascode/aws-cli:latest
    links:
      - sqs
    entrypoint: sh
    volumes:
      - ./:/project
      - ./create-queues.sh:/project/create-queues.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ENDPOINT_URL=http://sqs:9324
    command: " ./create-queues.sh"

  kinesis:
    image: dlsniper/kinesalite:latest
    ports:
      - "4567:4567"
  kinesis-create:
    image: infrastructureascode/aws-cli:latest
    links:
      - kinesis
    entrypoint: sh
    command: ./create-streams.sh
    volumes:
      - ./create-streams.sh:/project/create-streams.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ENDPOINT_URL=http://kinesis:4567
