service: activity-logs

frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "*"
plugins:
  - serverless-dynamodb-local
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline-sqs:
    endpoint: http://0.0.0.0:9324
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
  serverless-offline:
    lambdaPort: 4001
    httpPort: 3001
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  createLog:
    handler: handler.createLog
    events:
      - http:
          path: activityLogs
          method: post
      - sqs:
          arn: arn:aws:sqs:region:XXXXXX:ActivityLogsQueue

  listLogs:
    handler: handler.listLogs
    events:
      - http:
          path: activityLogs
          method: get
resources:
  Resources:
    ActivityLogsDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${env:ACTIVITY_LOGS_TABLE}
