service: products

frameworkVersion: "2"
useDotEnv: true
provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
custom:
  serverless-offline:
    lambdaPort: 4000
    httpPort: 3000

functions:
  createProduct:
    handler: src/handler.create
    events:
      - http:
          path: products
          method: post
  updateProduct:
    handler: src/handler.update
    events:
      - http:
          path: products/{id}
          method: put
  deleteProduct:
    handler: src/handler.delete
    events:
      - http:
          path: products/{id}
          method: delete
  getProduct:
    handler: src/handler.get
    events:
      - http:
          path: products/{id}
          method: get
  listProduct:
    handler: src/handler.list
    events:
      - http:
          path: products
          method: get
  searchProduct:
    handler: src/handler.list
    events:
      - http:
          path: searchProduct
          method: get
